# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 10:55
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0005_auto_20171203_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
