# Generated by Django 2.0.2 on 2018-02-27 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0006_notebook_unique_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='synced_desktop',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='synced_mobile',
        ),
    ]
