# Generated by Django 2.0.2 on 2018-03-02 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0008_auto_20180302_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='title_salt',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
