# Generated by Django 2.0.2 on 2018-03-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0009_notes_title_salt'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notebook',
            name='description_salt',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
