# Generated by Django 2.0.3 on 2018-03-17 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0010_auto_20180304_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='iteration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notes',
            name='iteration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
