# Generated by Django 2.0.3 on 2018-04-01 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0011_auto_20180317_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notebook',
            name='description_salt',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='iteration',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='iv',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='salt',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='iteration',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='iv',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='salt',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='title_salt',
        ),
    ]
