# Generated by Django 2.0.4 on 2018-04-04 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0012_auto_20180401_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
